#!/usr/bin/env python3
#Title: I.P
#Author: D~Myth

import os
import time

print("\033[2;33m[\033[2;37m•\033[2;33m] Installing Necessary Packages...\033[0m\n")
time.sleep(3.0)
os.system("apt update")
os.system("apt upgrade -y")
os.system("apt install python -y")
os.system("apt install figlet -y")
os.system("apt install bash -y")
os.system("apt install git -y")
os.system("apt install ruby -y")
os.system("gem install lolcat")
os.system("apt install nmap -y")
os.system("git clone https://github.com/XCHADXFAQ77X/XERXES")
os.system("git clone https://github.com/rajkumardusad/IP-Tracer")
os.system("chmod 777 *")
os.system("gcc -o xerxes /data/data/com.termux/files/home/I.P/XERXES/xerxes.c")
os.system("chmod +x /data/data/com.termux/files/home/I.P/IP-Tracer/install")
os.system("sh /data/data/com.termux/files/home/I.P/IP-Tracer/install")
os.system("cd /data/data/com.termux/files/home/I.P")
os.system("clear")
time.sleep(100.0)
print("\n\033[2;33m[\033[2;37m✓\033[2;33m]\033[2;32m DONE! \033[2;33mInstallation process completed!\n")
time.sleep(3.0)
os.system("clear")
time.sleep(0.5)
print(" \033[2;33m              ___________   ________  \033[0m")
time.sleep(0.5)
print(" \033[2;32m             (___     ___) |    __  \ ")
time.sleep(0.5)
print("  \033[2;33m                |   |     |   (__)  )\033[0m ")
time.sleep(0.5)
print("   \033[2;32m               |   |     |   _____/\033[0m")
time.sleep(0.5)
print("\033[2;33m               ___|   |___ _|  |\033[0m ")
time.sleep(0.5)
print(" \033[2;32m             (___________(_)__| \033[2;35m(v0.1)\033[0m\n")
time.sleep(1.0)
print("        \033[2;33m            ✰ By D~MYTH ✰   \n  ")
time.sleep(1.5)
print("               ➢ Now, to Launch tool, Run...\n")
time.sleep(1.5)
print("                  «« \033[2;35mpython ip.py \033[2;33m»»     \n  ")
os.system(" rm -rf ipinstall.py ")
